// <auto-generated />
using BookOrgWebapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookOrgWebapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418205455_AddGoogleAuthToUser")]
    partial class AddGoogleAuthToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookOrgWebapp.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ISBN", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            UserID = 1
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 1
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            UserID = 3
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 3
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 2
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Title", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ISBN");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            BookName = "How to Kill Men and Get Away With It"
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            BookName = "Let's Pretend This Never Happened"
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            BookName = "I'm Not the Only Murderer in My Retirement Home"
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            BookName = "99 Ways to Die: And How to Avoid Them"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "Jannika@gmail.com",
                            Name = "Annika"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "Clara@gmail.com",
                            Name = "Clara"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "Anna@gmail.com",
                            Name = "Anna"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Book", b =>
                {
                    b.HasOne("BookOrgWebapp.Models.Title", "Title")
                        .WithMany("Books")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookOrgWebapp.Models.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Title", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.User", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
