// <auto-generated />
using System;
using BookOrgWebapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookOrgWebapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407075756_FullDB")]
    partial class FullDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookOrgWebapp.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("AuthorID");

                    b.HasIndex("AuthorName")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            AuthorName = "Katy Brent"
                        },
                        new
                        {
                            AuthorID = 2,
                            AuthorName = "Jenny Lawson"
                        },
                        new
                        {
                            AuthorID = 3,
                            AuthorName = "Fergus Craig"
                        },
                        new
                        {
                            AuthorID = 4,
                            AuthorName = "Ashely Alker"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.BookAuthor", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.HasKey("ISBN", "AuthorID");

                    b.HasIndex("AuthorID");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            AuthorID = 1
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            AuthorID = 2
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            AuthorID = 3
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            AuthorID = 4
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.BookGenre", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ISBN", "Genre");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            Genre = "Fiction"
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            Genre = "Biography & Autobiography"
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            Genre = "Fiction"
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            Genre = "Health & Fitness"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Title", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN10")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailNormal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailSmall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            BookName = "How to Kill Men and Get Away With It",
                            Description = "Meet Kitty Collins. FRIEND. LOVER. KILLER.",
                            ISBN10 = "0008536694",
                            Language = "en",
                            PageCount = 0,
                            PublishedDate = new DateTime(2023, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "HQ Digital",
                            ThumbnailNormal = "http://books.google.com/books/content?id=3XZSzwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                            ThumbnailSmall = "http://books.google.com/books/content?id=3XZSzwEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api"
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            BookName = "Let's Pretend This Never Happened",
                            Description = "The #1 New York Times bestselling (mostly true) memoir from the hilarious author of Furiously Happy. “Gaspingly funny and wonderfully inappropriate.”—O, The Oprah Magazine When Jenny Lawson was little, all she ever wanted was to fit in. That dream was cut short by her fantastically unbalanced father and a morbidly eccentric childhood. It did, however, open up an opportunity for Lawson to find the humor in the strange shame-spiral that is her life, and we are all the better for it. In the irreverent Let’s Pretend This Never Happened, Lawson’s long-suffering husband and sweet daughter help her uncover the surprising discovery that the most terribly human moments—the ones we want to pretend never happened—are the very same moments that make us the people we are today. For every intellectual misfit who thought they were the only ones to think the things that Lawson dares to say out loud, this is a poignant and hysterical look at the dark, disturbing, yet wonderful moments of our lives. Readers Guide Inside",
                            ISBN10 = "0425261018",
                            Language = "en",
                            PageCount = 385,
                            PublishedDate = new DateTime(2013, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Penguin",
                            SubTitle = "A Mostly True Memoir",
                            ThumbnailNormal = "http://books.google.com/books/content?id=XVSLDQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                            ThumbnailSmall = "http://books.google.com/books/content?id=XVSLDQAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api"
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            BookName = "I'm Not the Only Murderer in My Retirement Home",
                            Description = "After a decades-long stint in prison, former serial killer Carol is looking to kick back and relax in her new retirement home...until a fellow resident drops dead and Carol has to prove she actually didn't do it this time.... Carol is delighted to be leaving her tiny prison cell behind to take her place in a luxury retirement home. She's hoping her past as a serial killer won't come to light so she can make a few friends and find some murder-free hobbies. But it's not long before a fellow resident—who happens to be a former police commissioner—drops dead, and Carol's true identity is leaked—making catching up over daily activities of bingo and baking rather awkward. Just her luck, Carol soon realizes that the victim wasn't the only former law enforcement officer at Sheldon Oaks—it's filled to the brim with former cops, barristers, and government representatives, her newfound friends included. And everyone thinks Carol's guilt is a no-brainer, but she is ready to prove them dead wrong...without killing anyone, for once.",
                            Language = "en",
                            PageCount = 273,
                            PublishedDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Penguin Group",
                            ThumbnailNormal = "http://books.google.com/books/content?id=DE1nEQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                            ThumbnailSmall = "http://books.google.com/books/content?id=DE1nEQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api"
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            BookName = "99 Ways to Die: And How to Avoid Them",
                            Description = "An illuminating, hilarious, and practical guide to 99 of the most terrifying ways to die and how to avoid them from an emergency medicine doctor. Dr. Ashely Alker is a self-described death escapologist—or, in more familiar terms, an emergency medicine doctor. She has seen it all, from flesh-eating bacteria to the work of a serial killer to the more mundane but no less deadly, and her work outwitting the end has uniquely prepared her to write this book. Dr. Alker manages to shock readers while making them laugh, educating them on how to outsmart a wide range of deadly situations and conditions. Many of the chapters include stories from her experiences in life and medicine, at times heartwarming, others heartbreaking. Sections include explorations of sex, poison, drugs, biological warfare, disease, animals, crime, the elements, and much more. An Anthony Bourdain-style greatest hits tour of death, 99 Ways to Die is entertaining while it informs. Full of valuable advice and wild stories, this riveting read might just save your life.",
                            ISBN10 = "1250359643",
                            Language = "en",
                            PageCount = 0,
                            PublishedDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "St. Martin's Press",
                            SubTitle = "And How to Avoid Them",
                            ThumbnailNormal = "http://books.google.com/books/content?id=lZ9eEQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                            ThumbnailSmall = "http://books.google.com/books/content?id=lZ9eEQAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "Jannika@gmail.com",
                            Name = "Annika"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "Clara@gmail.com",
                            Name = "Clara"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "Anna@gmail.com",
                            Name = "Anna"
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.UserBook", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ISBN", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("UserBooks");

                    b.HasData(
                        new
                        {
                            ISBN = "9780008536695",
                            UserID = 1
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 1
                        },
                        new
                        {
                            ISBN = "9798217189052",
                            UserID = 3
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 3
                        },
                        new
                        {
                            ISBN = "9780425261019",
                            UserID = 2
                        },
                        new
                        {
                            ISBN = "9781250359643",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("BookOrgWebapp.Models.BookAuthor", b =>
                {
                    b.HasOne("BookOrgWebapp.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookOrgWebapp.Models.Title", "Title")
                        .WithMany("BookAuthors")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.BookGenre", b =>
                {
                    b.HasOne("BookOrgWebapp.Models.Title", "Title")
                        .WithMany("BookGenres")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.UserBook", b =>
                {
                    b.HasOne("BookOrgWebapp.Models.Title", "Title")
                        .WithMany("UserBooks")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookOrgWebapp.Models.User", "User")
                        .WithMany("UserBooks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.Title", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookGenres");

                    b.Navigation("UserBooks");
                });

            modelBuilder.Entity("BookOrgWebapp.Models.User", b =>
                {
                    b.Navigation("UserBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
